# Generated by Django 5.2.9 on 2026-02-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=26)),
                ('uprofile', models.ImageField(blank=True, null=True, upload_to='user_profiles/')),
            ],
        ),
    ]
