# Generated by Django 5.2.9 on 2026-04-13 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcategory', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial')], max_length=30)),
                ('dname', models.CharField(max_length=30)),
                ('dstartprice', models.IntegerField()),
                ('dsummary', models.TextField()),
                ('dimage', models.ImageField(upload_to='interior')),
                ('dimage2', models.ImageField(blank=True, null=True, upload_to='interior')),
                ('dimage3', models.ImageField(blank=True, null=True, upload_to='interior')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': 'Interior Project',
                'verbose_name_plural': 'Interior Projects',
                'unique_together': {('user', 'dname')},
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('site_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=50)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.user')),
                ('dreamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.user')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.designer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.site')),
            ],
        ),
        migrations.CreateModel(
            name='Moodboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.designer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'unique_together': {('user', 'design')},
            },
        ),
    ]
